fix pr workflow

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -29,9 +29,18 @@ jobs:
       - run: pnpm test
 
       - uses: actions/upload-artifact@v3
+        if: ${{ always() }}
         with:
           name: junit test report
           path: junit.xml
+
+      - name: Handle test failure
+        if: ${{ failure() }}
+        shell: bash
+        run: |
+          set -x
+          echo "Unit test failed on previous step, returing error"
+          exit 1
 
   code-quality:
     name: Code quality
